### ISSUE TITLE
dose it support built on Windows with Visual studio?

### ISSUE THREAD

**Issue by EthanHee** [cryptozeny/cpuminer-opt-sugarchain#27]

**Comment by decryp2kanon** [comment]
please use this

https://github.com/cryptozeny/cpuminer-opt-sugarchain/releases/tag/v3.8.8.1.7rc1

**Comment by decryp2kanon** [comment]
dunno about VS. because i do not use windows

**Comment by EthanHee** [comment]
if so, how do you make the exe binary file?

**Comment by decryp2kanon** [comment]
cross compile on linux

**Comment by decryp2kanon** [comment]
https://github.com/cryptozeny/cpuminer-opt-sugarchain/blob/master/winbuild-cross.sh

**Comment by EthanHee** [comment]
is there a install guide for how to  make the exe binary file through the source files?

**Comment by EthanHee** [comment]
OK , i will try  ,thank you

**Comment by EthanHee** [comment]
this is how i  do it :
```
1、 git clone git@github.com:cryptozeny/cpuminer-opt-sugarchain.git
2、cd cpuminer-opt-sugarchain/
3、./winbuild-cross.sh
```

then come errors:
```
/work/miners/cpuminer-opt-sugarchain/depends/curl-7.47.0/include/curl/curlbuild.h:122:23: fatal error: windows.h: 没有那个文件或目录
In file included from /work/miners/cpuminer-opt-sugarchain/depends/curl-7.47.0/include/curl/curl.h:34:0,
                 from util.c:27:
/work/miners/cpuminer-opt-sugarchain/depends/curl-7.47.0/include/curl/curlbuild.h:122:23: fatal error: windows.h: 没有那个文件或目录
In file included from /work/miners/cpuminer-opt-sugarchain/depends/curl-7.47.0/include/curl/curl.h:34:0,
                 from miner.h:45,
                 from sysinfos.c:12:
/work/miners/cpuminer-opt-sugarchain/depends/curl-7.47.0/include/curl/curlbuild.h:122:23: fatal error: windows.h: 没有那个文件或目录
```


how can i save it?

**Comment by decryp2kanon** [comment]
which linux do you use?

**Comment by EthanHee** [comment]
Ubuntu 18.04

**Comment by decryp2kanon** [comment]
```bash
sudo apt-get install -y \
build-essential libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev automake zlib1g-dev && \
git clone https://github.com/cryptozeny/cpuminer-opt-sugarchain.git && \
cd cpuminer-opt-sugarchain && \
./build-yespower.sh && \
./cpuminer --cputest
```

**Comment by EthanHee** [comment]
@decryp2kanon  
```
sudo apt-get install -y \
build-essential libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev automake zlib1g-dev && \
git clone https://github.com/cryptozeny/cpuminer-opt-sugarchain.git && \
cd cpuminer-opt-sugarchain && \
./build-yespower.sh && \
./cpuminer --cputest
```
I can use those commands to build On ubuntu 18.04,and  get the Executable file used on ubuntu correctly.


But My problem is that `I can not get the Executable file used on Windows correctly`
